# Generated by Django 6.0.1 on 2026-01-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0069_alter_project_contribution_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecthealthmetrics",
            name="is_level_compliant",
            field=models.BooleanField(
                default=True,
                help_text="Designates if the local project level matches the official OWASP source.",
                verbose_name="Is level compliant",
            ),
        ),
    ]
