# Generated by Django 6.0.1 on 2026-01-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owasp", "0070_projecthealthmetrics_is_level_compliant"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecthealthrequirements",
            name="is_level_compliant",
            field=models.BooleanField(
                default=True,
                help_text="Designates if the project level must match the official OWASP source.",
                verbose_name="Is level compliant",
            ),
        ),
    ]
